name: easypaisa_with_rsa_encryption
description: Introducing a seamless and secure Flutter package designed to integrate Easypaisa, one of Pakistan's leading payment gateways, into your mobile applications. This package simplifies the process of handling payments while ensuring top-notch security through RSA Encryption, safeguarding sensitive user data during transactions.
version: 1.2.0
homepage: https://github.com/chaudhry7779/Easypaisa_With_RSA_Encryption_Flutter
repository: https://github.com/chaudhry7779/Easypaisa_With_RSA_Encryption_Flutter.git
issue_tracker: https://github.com/chaudhry7779/Easypaisa_With_RSA_Encryption_Flutter/issues

environment:
  sdk: '>=3.5.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  pointycastle: ^3.7.0 # For RSA encryption and signing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0